```{r}
library(sf)
library(janitor)
library(dplyr)
library(tmap)
library(tmaptools)
library(showtext)
library(rmapshaper)
library(here)
font_add_google("Fira Sans")
showtext_auto()
```

# Load data

```{r}
# load bus
bus_routes <- st_read(here("data","routes.geojson"))%>%
  simplify_shape(., fact = 0.1) 

# load Singapore
singa_shape <- st_read(here("data","singabound","SGP_adm0.shp"))%>%
  simplify_shape(., fact = 0.1)
```

# Draw map

```{r}
map_title = "Singapore Bus Route Density"
sources = "LTA Singapore"

map <-
  tm_shape(singa_shape) +
  tm_fill(col = "darkblue") +
  tm_borders(col = "white", lwd = 3) +
  
  tm_shape(bus_routes) +
  tm_lines(col = "white",
           lwd = 6,
           alpha = 0.02) +
  
  tm_shape(bus_routes) +
  tm_lines(col = "white",
           lwd = 3,
           alpha = 0.02) +
  
  tm_shape(bus_routes) +
  tm_lines(col = "white",
           lwd = 2,
           alpha = 0.02) +
  
  tm_shape(bus_routes) +
  tm_lines(col = "white",
           lwd = 1,
           alpha = 0.5) +

  # tm_compass(
  #   type = "8star",
  #   show.labels = FALSE,
  #   color.dark = "gray40",
  #   size = 3,
  #   position = c(0.8, 0.1),
  # ) +
  tm_credits(
    paste("Shaun Hoang | Source:", sources, sep = " "),
    col = "gray40",
    size = 1,
    position = c(0.595, 0.07)
  ) +
  tm_layout(
    bg.color = "white",
    scale = 1,
    frame = FALSE,
    fontfamily = "Fira Sans",
    title = map_title,
    title.color = "gray20",
    title.size = 1.5,
    title.position = c(0.6, 0.15),
    title.bg.color = "white"
  )
map

```

```{r}
tmap_save(map,filename = here("output","day6.jpg"),width=1920)
```
